# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180115_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_type',
            new_name='audio_file',
        ),
    ]
